name: EPG Update
on:
  push:
  schedule:
    - cron: '0 4,10,22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update EPG Files
      run: |
        rm -f e.xml && wget https://epg.112114.xyz/pp.xml -O EPG.xml
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add EPG.xml
        git commit -m "EPG Automatic Update."
    - name: Push changes
      run: git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
